### ISSUE TITLE
Implement flag to allow running bot in "no processing" mode for testing

### ISSUE THREAD

**Issue by gsilvapt** [surface-security/django-slack-processor#17]
https://github.com/surface-security/django-slack-processor/blob/b830d0aab774607a3dea022e16668e4bd05e4dae/slackbot/base.py#L11

This command should include a flag to control whether the messages are processed or not. This is useful when we need to run the bot in an environment we need it running but not processing the messages. Additionally, there should be backward compatibilities because it should *not* alter behavior.

**Comment by fopina** [comment]
That flag is specific to each MessageProcessor implementation to define whether or not it handles its own messages.

I don’t recall why it was added (nor why a processor would want to handle messages generated by the bot itself) but it doesn’t sound like the issue you’re trying to solve right?

You want a flag to run slack bot without enabling any MessageProcessor right?

**Comment by gsilvapt** [comment]
One idea is to have this setting in the UI so we can enable or disable the bot as we need. Which made us wonder whether this should be implemented only for those who need it instead of here.

**Comment by fopina** [comment]
Just to reiterate, setting should not affect this attribute but instead just skip whole processing in the run_bot management command.

I suppose that’s a quick way to have it in the UI assuming setting is set using dynamic settings, but it feels rather odd to have a setting that disables the entire purpose of a command instead of just stopping the command…

maybe that could be done in a wrapper management command directly in Surface instead?

* create command with same name as this one (so it overrides this)
* Subclass this one and re-implement the relevant loop considering the setting

**Comment by fopina** [comment]
I don’t think it should go into this package, for adding dependency nor for not making any sense out of a specific context.

most setups might be able to just shut down the command from UI (not surface, infra UI).

> maybe that could be done in a wrapper management command directly in Surface instead?

my suggestion was this, internal or public, but in Surface project; not in the package

**Comment by gsilvapt** [comment]
Yep, we're aligned. Closing this issue then. Thanks for your help!
